nimblehq/ios-templates

__PROJECT NAME__/__PROJECT NAME__.xcodeproj/xcshareddata/xcschemes/__PROJECT NAME__ debug.xcscheme
__PROJECT NAME__/__PROJECT NAME__.xcodeproj/xcshareddata/xcschemes/__PROJECT NAME__ staging.xcscheme
__PROJECT NAME__/__PROJECT NAME__.xcodeproj/xcshareddata/xcschemes/__PROJECT NAME__.xcscheme

I created shared schemes for our 3 build configurations. This includes:
```
- __PROJECT NAME__
- __PROJECT NAME__ staging
- __PROJECT NAME__ debug
```
the first scheme is set with `release` configuration and doesn't include testing in the scheme. The others are as its name says, with testing included.
This closes #12

include shared schemes to the template

---

__PROJECT NAME__/Podfile
__PROJECT NAME__/__PROJECT NAME__.xcodeproj/project.pbxproj
__PROJECT NAME__/__PROJECT NAME__/Application/AppDelegate.swift
__PROJECT NAME__/__PROJECT NAME__/Application/Infos/Info.plist

I configured project file to support Crashlytics and Fabric in our template project. Added them into our `podfile`, and also updated the Bakery script, which now supports automatic Cocoapods installation right after project generation. ✌🏻

Support Crashlytics and Fabric Beta

---

__PROJECT NAME__/__PROJECT NAME__.xcodeproj/project.pbxproj

For sending `Debug` target to crashlytics, we need to send dSYM with it. So this is require in build setting. 
will close #20

Set Export dSYM for all Target

---

__PROJECT NAME__/fastlane/Developer Portal/Codefile

Apple developer portal doesn't support to create app id `name` with `-`. 
So I add gsub `ruby`  in fastlane to replace `-` with ` ` ( space ). 
#32

ensure remove - from app name

---

__PROJECT NAME__/.swiftlint.yml

I just made some configurations for our SwiftLint rules. I think we should exclude `id` from `identifier_name` rule, which only allow variable name to be up to 3 characters or more. Also, we should remove disabling `traling_whitespace` rule.

Configure SwiftLint rules

---

__PROJECT NAME__/.gitignore

- `.DS_Store` always added as untracked file while working on the repository.
- `.p12` was added after `cert` and `sigh` which shouldn't commit to repository with unencrypted.
- I added `.DS_Store` and `.p12` to git ignore file.
close #35

Ignore .DS_Store and p12

---

README.md
__PROJECT NAME__/fastlane/Developer Portal/Codefile

- After setup the project, then we need the app id for code signing 
- These lanes will create AppID on `Developer portal` with project name that set.

Create AppID helper lane

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

https://github.com/nimble/git-templates/issues/70
- We have no template file for pull request and issue creation yet. 
- add template file 
close #70

[#70] Add issue and pr template file

---

__PROJECT NAME__/fastlane/.env

https://github.com/nimbl3/ios-templates/issues/69
- Fastlane generated keychain on ci with `-${BRANCH_NAME}`
- The expected name is `${REPOSITORY_NAME}-${BRANCH_NAME}` 
- `REPOSITORY_NAME` is invalid order, it's used before define this env variable.  
close #73

[#69] Invalid keychain name on ci machine. 

---

README.md
__PROJECT NAME__/Jenkinsfile
__PROJECT NAME__/fastlane/CI/CIfile
__PROJECT NAME__/fastlane/Fastfile

- I created shared Jenkins function on [jenkins-pipeline-shared](https://github.com/nimbl3/jenkins-pipeline-shared)
- Now we have `shouldSkipDeploy()`, `shouldSkipCI()`, `getCommitMessage()` `containsCommitMessage()` as helper function without importing. 
- Update `ci-skip` to `skip-ci` because now we have `skip-deploy` so I rename `ci-skip` to `skip-ci` following deploy
- Remove Internal helper function.  
close #79

[#79] change keyword `ci-skip` to `skip-ci`

---

.editorconfig
Nimble Templates/App.xctemplate/TemplateInfo.plist
Nimble Templates/iOS Blank.xctemplate/TemplateInfo.plist
Nimble Templates/iOS Sources.xctemplate/TemplateInfo.plist
Nimble Templates/iOS Tests.xctemplate/TemplateInfo.plist
Nimble Templates/temp/.gitignore
install.sh

https://github.com/nimbl3/ios-templates/issues/106
We already have the standard file organization for iOS template on wiki: https://github.com/nimblehq/ios-templates/wiki/Standard-file-organization-🗂
Please config the structure into App.xctemplates
Configure file `TemplateInfo.plist` to create our structure folders
Note: A good resource to follow - https://useyourloaf.com/blog/creating-custom-xcode-project-templates/
We can do this in 2 ways
- Group (Yellow): at current research status, it's only possible to create yellow folder with file inside, not an empty one.
- Folder (Blue): possible to create blue folder without file and also easier to create.
We're using yellow folder but could change to blue one. We also can use a script to remove those file instead.

[106] As an iOS developer, I can see the structure of project after create it from iOS template

---

Nimble Templates/App.xctemplate/TemplateInfo.plist
README.md

https://github.com/nimblehq/ios-templates/issues/111
As an iOS developer, I can see 6 build configurations and 4 custom flags after create project from iOS project templates.
**Flags and build configurations must follow following rules:**
Configurations / Custom flags | DEBUG | UAT | Staging | Production
-- | -- | -- | -- | --
Dev UAT | x | x |   |  
UAT |   | x |   |  
Dev Staging | x |   | x |  
Staging |   |   | x |  
Dev Production | x |   |   | x
Production |   |   |   | x
Added build configurations:
- Dev Staging
- Staging
- Dev UAT
- UAT
- Dev Production
- Production
Add flags:
- DEBUG
- UAT
- STAGING
- PRODUCTION

[111] Build configurations and custom flags

---

Nimble Templates/App.xctemplate/TemplateInfo.plist

https://github.com/nimbl3/ios-templates/issues/113
We should enable build with bitcode for Production only.
| | Enable Bitcode |
|---|---|
| Dev UAT |  |
| UAT |  |
| Dev Staging |  |
| Staging |  |
| Dev Production |  |
| Production | x |

[113] As an iOS developer, we should enable build with bitcode for Production only

---

Nimble Templates/App Base.xctemplate/TemplateInfo.plist
Nimble Templates/App.xctemplate/TemplateInfo.plist
Nimble Templates/Bundle Base.xctemplate/TemplateInfo.plist
Nimble Templates/Cocoa Touch App Base.xctemplate/TemplateInfo.plist

https://github.com/nimbl3/ios-templates/issues/124
👆
Bundler identifier not takes configured identifier in Nimble iOS template. Instead it takes bundle identifier from `com.apple.dt.unit.bundleBase`
which disabled our bundle identifier configurations.
Describe in details how to test the changes; referenced documentation is welcome as well.

[124] Configured bundle identifiers not set to bundle identifiers of newly created project.

---

Nimble Templates/App.xctemplate/TemplateInfo.plist

https://github.com/nimbl3/ios-templates/issues/119
Add correct file structure for SceneDelegate.swift in Interface: SwiftUI, Lifecycle: UIKit.
When using Interface: SwiftUI, Lifecycle: UIKit, SceneDelegate.swift will now generated. correctly. However still not support SwiftUI lifecycle.

[119] Fix SceneDelegate.swift is not initialized correctly after creating a new project with SwitfUI

---

.github/PULL_REQUEST_TEMPLATE/RELEASE_TEMPLATE.md

Add the Github template for the release pull requests that match Nimble's [convention](https://nimblehq.co/compass/development/version-control/release-management/#release-pull-request).
It's part of the [engineering initiative](https://www.notion.so/nimblehq/Define-the-Release-Pull-Request-Template-Github-for-All-Platform-Templates-71d1bd13afa8456b8e8dda6a7f002801).
The implementation is identical with https://github.com/nimblehq/git-template/pull/15. 
Github supports multiple [templates for issues and pull requests](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates). For example, to define multiple pull request templates, simply define them like this:
```bash
.github
└── PULL_REQUEST_TEMPLATE
├── …
```

Add the Github release PR template

---

Tuist/ProjectDescriptionHelpers/ProjectBuildConfiguration.swift
Tuist/ProjectDescriptionHelpers/Scheme+Initializing.swift

https://github.com/nimblehq/ios-templates/issues/179
There are bugs that won't allow us to create a new project with the  ios template:
- Incorrect xcconfig path.
- Incorrect setup of build configuration for schemes.
- Fix computed property path in `ProjectBuildConfiguration` enum.
- Update build configuration for schemes in `Scheme+Initializing`

[179] Incorrect build configuration setup

---

.swiftlint.yml

https://github.com/nimblehq/ios-templates/issues/189
Ignore swiftlint check in  `./DerivedData`
n/a
n/a

[#189] [Chore] Fix swiftlint errors in DerivedData breaks Fastlane

---

{PROJECT_NAME}/Sources/Constants/Constants+API.swift
{PROJECT_NAME}/Sources/Supports/Extensions/UIKit/Color+Application.swift
{PROJECT_NAME}/Sources/Supports/Helpers/Typealiases/Typealiases.swift

close #221 
Add ignore file_name to extension
These files would never conform to `file_name` rule by their nature.
Wait for CI.

[#221] Include ignore SwiftLint file_name for extensions Files.

---

fastlane/Fastfile
fastlane/Managers/TestManager.rb

close #220 
Use fastlane scan with build and test instead of separate build
Currently there is no need to separate build and test in fastlane scan.

[#220] Pull Request review Workflow seems to be failing

---

.swiftlint.yml
Tuist/ProjectDescriptionHelpers/TargetAction+Initializing.swift
make.sh

https://github.com/nimblehq/ios-templates/issues/208
- Add `R.generated.swift` reference into Xcode project
Due to `R.generated.swift` is ignored, it will be added before Tuist generates into `make.sh`

[#208] Fix: R.generated.swift need to be created to include into project

---

.github/workflows/publish_docs_to_wiki.yml
.gitignore

https://github.com/nimblehq/ios-templates/issues/235
In the publish_docs_to_wiki workflow, it's triggered with the main branch, however, this repository has a master branch instead, we need to update the workflow.
- Add `master` branch into the workflow
N/A

[#235] Fix: Add master branch for trigger publish_docs_to_wiki workflow

---

docs/Standard-File-Organization.md
docs/_Sidebar.md

Resolves #226
As we have https://github.com/nimblehq/ios-templates/pull/224 that supports publishing docs to the wiki, we need to bring all iOS templates' documents into the repository's source.
Add document into the folder docs
Brings document from the Notion page into the repository's source: Standard File Organization.

[#226] Add standard file organization content

---

fastlane/Fastfile
fastlane/Managers/MatchManager.rb

https://github.com/nimblehq/ios-templates/issues/250
- Update `adhoc` provisioning profile when registering a new device
- Add sync development provisioning profile lane
- When turning on the `Push Notifications` feature, the development environment will require property provisioning profiles, so we will need to create and sync these provisioning profiles to be able to build and debug
- For new updates on `register_new_device`,  I am unable to test due to don't having an Apple Developer account
<details>
<summary>bundle exec fastlane sync_development_signing</summary>
```
[✔] 🚀 
+------------------------+---------+------------------------+
|                       Used plugins                        |
+------------------------+---------+------------------------+
| Plugin                 | …
```

[250] [Bug] Fix: Only update development profiles when registering a new device

---

.github/CODEOWNERS

Add `CODEOWNERS` in the subdirectory `.github`
All project template repositories now have official leads so it is crucial to have it documented. In addition, this will ensure that all concerned developers are notified when new pull requested are created ✌️

Add the project's maintainers info

---

.github/CODEOWNERS

Update the CODEOWNERS file in the subdirectory `.github` to support adding all reviewers from the iOS chapter.
- Add @suho to the list. This will ensure that all concerned developers (including Team Lead) are notified when new pull requests are created ✌️

Update the project's maintainers info

---

bitrise.yml

https://github.com/nimblehq/ios-templates/issues/259
In the fastfile we're having the following lanes
`build_and_upload_staging_app`
`build_and_upload_production_app`
So we can replace steps `xcode_archive`, `firebase_app_distribution`, `firebase_dsym_upload` with single lane `build_and_upload_staging_app` in `deploy_staging workflow` and `build_and_upload_production_app` in `deploy_release_firebase` workflow
- Replace Bitrise's readymade steps for build, set build number and upload to AppStore/Firebase with our Fastlane lane
- Fix indentation at `deploy_staging` workflow
[apps_f0f33e48167c2b26_1b703517-4a38-4d9a-b950-6ff83c42b243-full.txt](https://github.com/nimblehq/ios-templates/files/8485881/apps_f0f33e48167c2b26_1b703517-4a38-4d9a-b950-6ff83c42b243-full.txt)

[#259] Update Bitrise workflow to use Fastlane

---

Podfile

Resolves #269 
With the Sourcery version 1.8.1, we can't install it on CI.
- Specific the version of Sourcery to `1.8.0`
to be provided

[#269] Fix: Version of Sourcery

---

.github/wiki/Project-Dependencies.md
.github/wiki/_Sidebar.md

Resolve #228
As we have a workflow that supports publishing docs to the wiki, we need to bring all iOS templates' documents into the repository's source.
Add document into the folder wiki
Brings document from [the Notion page](https://www.notion.so/nimblehq/Project-Dependencies-08ff1d14d4e7486daf2b54387c6e6e25) into the repository's source

[#228] Add Project Dependencies document

---

.github/wiki/Project-Configurations.md
.github/wiki/Standard-File-Organization.md
.github/wiki/_Sidebar.md

Resolve #227 
As we have a workflow that supports publishing docs to the wiki, we need to bring all iOS templates' documents into the repository's source.
- Add document into the folder wiki
- Brings document from [the Notion page](https://www.notion.so/nimblehq/Project-Configurations-e66e3e19ecc541028c605481b28b1bd0) into the repository's source

[#227] Add Project Configurations document

---

.github/wiki/Github-Actions.md
.github/wiki/_Sidebar.md

close #229 
Add document into the folder .github/wiki
Brings document from [the Notion page](https://www.notion.so/nimblehq/Github-Actions-d009345c7ffb40768fb81d316a46984f) into the repository's source:

[#229] Add Github Actions Templates document

---

make.sh

https://github.com/nimblehq/ios-templates/issues/275
Install script currently does not accept "-" symbol inside the package name. We must update regex to allow that case.
Update regex for package name validation

[#275] Fix: Package name contains "-" symbol is invalid while running install script

---

.github/wiki/Bitrise.md
bitrise.yml

https://github.com/nimblehq/ios-templates/issues/284
Currently, the deploy workflow from Bitrise templates is triggered only for the master branch, we need to support the main branch also.
- Add a new trigger that will run the `deploy_app_store` workflow when `main` branch is updated.
- Update the Bitrise template document to reflect the change on the trigger map.

[#284] Add trigger when `main` branch is updated

---

.github/wiki/Bitrise.md
bitrise.yml

https://github.com/nimblehq/ios-templates/issues/293
Currently, the lane run_xcov does not exist in Fastfile. It was removed in PR https://github.com/nimblehq/ios-templates/pull/242. So we should remove where the lane run_xcov is used.
In this PR, I removed where the lane `run_xcov` is used in `bitrise.yml` and `Bitrise.md`.

[#293] [Bug] Fix: There is no lane name run_xcov in Fastfile

---

.github/wiki/Bitrise.md
bitrise.yml

https://github.com/nimblehq/ios-templates/issues/296
According to [this comment](https://github.com/nimblehq/ios-templates/pull/295#discussion_r895304282), we should add a step to clean up previous code coverage report into `bitrise.yml` to keep the consistency between the Bitrise and Github Action workflows.
N/A

[#296] [Bug] Fix: Add step to clean up previous code coverage report into bitrise.yml 

---

.github/workflows/publish_docs_to_wiki.yml

https://github.com/nimblehq/ios-templates/issues/286
The publish docs to wiki workflow is triggered on push with the path docs/**, however, we changed the path to .github/wiki, we need to update that
N/A

[#286] [Bug] Fix: The trigger setup for the publish docs to wiki workflow

---

.github/wiki/Project-Configurations.md

Resolve #279 
As Bliss suggested, the document might be improved if we add a section break between the top (Project terminology) and bottom (Build configuration that we predefined for the user of the template) to add some sense that we are shifting the content to another topic.

[#279] [Chore] Improve Project Configuration content

---

.github/wiki/_Sidebar.md

https://github.com/nimblehq/ios-templates/issues/290
It needs to update the wiki of ios-template, following [Nimble's Github Wiki convention](https://nimblehq.co/compass/development/documentation/github-wiki/).
In this PR: 
- I move the following documents from  the `Infrastructure` section into the `Architecture` section, according to [this comment](https://github.com/nimblehq/ios-templates/commit/49e4b39f8a195e5004117372cb54f85676a2524f#commitcomment-76307423):
- Standard File Organization
- Project Configurations
- Project Dependencies
N/A

[#290] [Chore] Update Github Wiki following the convention

---

Dangerfile

https://github.com/nimblehq/ios-templates/issues/312
Currently, we are running `xcode_summary` on whole the file in the project which could lead to repeat warnings on every PR, and that makes it hard for the reviewer to focus on the new warnings produced by changed files. There is a solution for this case that we can use `xcode_summary.ignored_results` to specify which result can be ignored, in our case they are unchanged files.
The following code is added to the `Xcode Summary` section in the Danger file for ignoring changed files:
```
changed_files = (git.modified_files - git.deleted_files) + git.added_files
xcode_summary.ignored_results { |result|
if result.location
not changed_files.include?(result.location.file_path)
else
true
end
}
```
Only changed file is reported and notified: …

[#312] Run `xcode_summary` on changed files only in Danger

---

.github/workflows/deploy_AppStore.yml
.github/workflows/deploy_Firebase.yml
.github/workflows/deploy_Release_Firebase.yml

Resolves #288 
Add `workflow_dispatch` to manually trigger deploy workflows.
Here is `workflow_dispatch` documentation: 
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
- https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
NOTE: To trigger the workflow_dispatch event, your workflow must be in the default branch
`N/A`

Add `workflow_dispatch` to manually trigger deploy workflows

---

.swiftformat
.swiftlint.yml

https://github.com/nimblehq/ios-templates/issues/322
Add SwiftLint rules to check for multiline arguments.
Add SwiftFormat rules to format code blocks.
**Known bug**:
If array has init with multiple arguments, lint will not be able to catch it.
```
[
Item("a", "b"), Item("A", "b), // lint will not be able to catch this one.
Item("a", "c")
]
```
https://user-images.githubusercontent.com/6356137/185343080-4bab077a-493f-476b-af85-36f65f7cc848.mov

[#322] Add Multiline Parameter Lint

---

fastlane/Fastfile
fastlane/Managers/MatchManager.rb

https://github.com/nimblehq/ios-templates/issues/301
- Pass `DeliverableConstants.DEV_PORTAL_APPLE_ID` to `MatchManager` and `register_new_device` lane
n/a

[#301] [Fix] Constants.DEV_PORTAL_APPLE_ID is unused by mistake

---

fastlane/Constants/Constant.swift
fastlane/Fastfile.swift
fastlane/Helpers/Build.swift
fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj/project.pbxproj

Resolves #333 
- Provide 3 lanes for building:
- AdHoc Staging
- AdHoc Production
- App Store
- Create `Build` to support preparing parameters before making the build.
- Fastlane set `xcodebuildFormatter` with default option named `xcbeautify`, however, it doesn't work  after appending to  `xcodebuild` command. So I change it to `xcpretty`.
- For `exportOptions`, if we want to test on ios-template's generated app, we should comment current one, and uncomment `Constant.bundleId: "match \(type.method) \(Constant.bundleId)"` since our `bundle id` is not match with the design. Something like: Staging's bundle id should be `xxx.staging` but our ios-template's app is using without suffix `staging`.

[#333] As a developer, I can build the project with the adhoc and appstore methods with Fastlane Swift

---

.swiftlint.yml

https://github.com/nimblehq/ios-templates/issues/355
Fix false linting when function includes multi items generics `<T, U>`.
Ignore multi items generics in multiline argument. Only affect generics in multiline only.
Before
After

[#355] Fix: Multi parameters func trigger wrongly for parameter with generics <T,U>

---

fastlane/Constants/Constant.swift
fastlane/Fastfile.swift
fastlane/Helpers/Build.swift
fastlane/Helpers/Distribution.swift
fastlane/Helpers/Keychain.swift
fastlane/Helpers/Match.swift
fastlane/Helpers/Symbol.swift
fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj/project.pbxproj

Resolves #339 
- Added the `uploadToCrashlytics` function to support uploading the dSYMs to Firebase
- Update the project's constants to use values from the generated project script.
- I changed from `class` to `enum` as we are using it as namespaces. With class, we are allowing the developer to init which does not make sense.
- I created `enum Symbol` to support uploading the dSYMs to Firebase based on environment (Staging/Production)
- I also added an extra logic to check if the file dSYMs exists or not.

[#339] As a developer, I can upload dSYM file to Firebase with Fastlane Swift

---

fastlane/Constants/Constant.swift
fastlane/Fastfile.swift
fastlane/Helpers/Symbol.swift

Resolve #340
Add functions to support downloading dSYM files from AppStore
- I added a function to support downloading dSYM file from AppStore and uploading it to Firebase.
- Because of the file name, there will be 2 functions for uploading, one for ad hoc and one for the app store method.

[#340] As a developer, I can download dSYM file from AppStore with Fastlane Swift

---

.gitignore
fastlane/Constants/Constant.swift
fastlane/Fastfile.swift
fastlane/Helpers/Distribution.swift

#337
- At `Distribution`, add TestFlight uploading function.
- At `Fastfile`, add upload build to TestFlight lane.
- Since FastlaneRunner is an executable file and it's changed over time when building Fastlane swift project, so we don't need to commit to source code. I added it to `gitignore`.
- Also added the `Output` folder into `gitignore`.

[#337] As a developer, I can upload the build to TestFlight with Fastlane Swift

---

fastlane/Constants/Constant.swift
fastlane/Fastfile.swift
fastlane/Helpers/Version.swift
fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj/project.pbxproj

Resolves #342 
- Created `get` and `set` functions for build and version numbers.
- Created `enum Version` that contains set and get functions.
- Created private helper function `setAppVersion` and `bumpToVersion`.
- Added  `manualVersion` variable to `Constant`, developer can set manual version app directly or leave it empty.
- Added project path variable to `Constant`.
**Setting, getting functions:**
**private helper function:**

[#342] As a developer, I can get and set build number and version number of the project with Fastlane Swift

---

fastlane/Constants/Constant.swift
fastlane/Fastfile.swift
fastlane/Helpers/Test.swift
fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj/project.pbxproj

Resolves #341 
- Create a lane for building and testing project using `scan`() in fastlane.
- Created `enum Test`contains `buildAndTest` function.
- Added some variables `device`, `testTarget`, `uiTestTarget`, `testOutputDirectoryPath` to `Constant`.
**onSuccess:**
**Test output .xcresult file:**

[#341] As a developer, I can build and test the project with Fastlane Swift

---

fastlane/Fastfile.swift

#343 
- Create a lane to register new device using `registerDevice()`.
- Implement `registerDevice` lane that matches [current ruby implementation](https://github.com/nimblehq/ios-templates/blob/5664de6fc4a9da259295c4c1a1d3841d69b1dd72/fastlane/Fastfile#L89).
- `registerDevice` lane requires `device name`, `UDID`, `teamID` to register a new device.

[#343] As a developer, I can register new device with Fastlane Swift

---

fastlane/Constants/Constant.swift
fastlane/Fastfile.swift

#347 
- Created utility functions to clean up xcov output and derived data.
- `cleanUpDerivedData` function for clean up derived data at path `./DerivedData`.
- `cleanUpXcov` function for cleaning up output of xcov at path `./fastlane/xcov_output`.

[#347] As a developer, I can have a lane in Fastfile.swift for clean up data

---

README.md

#348 
- Update the logo to support the light/dark mode follow git-template
- Update the logo in README file follow Nimble's git-template
**Light Theme Default**
**Dark Theme Default**

[Chore] [#348] Update README file according to the git-template

---

.github/workflows/deploy_AppStore.yml
.github/workflows/deploy_Firebase.yml
.github/workflows/deploy_Release_Firebase.yml
bitrise.yml
fastlane/Constants/Environments.rb
fastlane/Fastfile
fastlane/Managers/EnvironmentManager.rb

close #351
Add a step to upload `dsym` and `ipa` file to CICD.
- GitHub Actions: Upload files as artifact.
- Bitrise: Upload files as artifact.
- Create a new fastlane helper `EnvironmentManager`  for saving build contexts: version, build number, files locations, to CICD.
- Use `EnvironmentManager` in `build_and_upload_appstore_app`, `build_and_upload_production_app`, and `build_and_upload_staging_app` to save lanes' output.
- Add `upload-artifact` to GitHub Actions to upload artifacts.
- GH Actions, there's an `.archive` file inside folder `./Build` so IPA and DSYM need to be specified individually to save space.
- Add `deploy-to-bitrise-io` to Bitrise to upload artifacts.
https://github.com/blyscuit/ios-template-upload-build/actions/runs/3393119685

[#351] Add steps in CI/CD templates to support upload builds and dSYM files to build artifacts of CI/CD platforms (Github Actions, Bitrise)

---

fastlane/Fastfile.swift

- Resolves #345
I created lanes in the `Fastfile.swift` to support [code signing](https://github.com/nimblehq/ios-templates/blob/master/fastlane/Fastfile?rgh-link-date=2022-09-16T04%3A49%3A14Z#L59) for the project with different methods and ids
- I used `syncCodeSigning` from `Match` to support code signing.
Just run this on the terminal
```sh
$ bundle exec fastlane syncDevelopmentCodeSigningLane --disable_runner_upgrades
```

[#345] As a developer, I can have lanes in Fastfile.swift for sync match the project

---

fastlane/Fastfile.swift
fastlane/Helpers/Build.swift
fastlane/Helpers/Symbol.swift

- Resolves #346
- Implement full functionality of build and upload builds to Firebase and App Store.
- Because of Xcode14, we are now removing the download dSYM files from App Store (disable bit code). So I updated it in this pull request to support build and upload lanes.
- I also move all private helper function to the bottom.

[#346] As a developer, I can have lanes in Fastfile.swift for building and uploading

---

.github/workflows/test_upload_build_to_test_flight.yml
Podfile
fastlane/Fastfile
fastlane/Managers/BuildManager.rb

Update Project for Xcode 14.
- Some library will result in additional `bundle` and have to disable signing via `podfile`. https://stackoverflow.com/a/74129238/3736373
- Remove `bitcode` from `BuildManager` because bitcode will fail TestFlight upload.
- `macOS-latest` is [macOS-11](https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md) and does not have Xcode 14. We should change to `macOS-latest` when Actions update the default https://github.com/actions/runner-images/issues/6384.
https://github.com/nimblehq/ios-templates/actions/runs/3416880487

[Chore] Update Project for Xcode 14

---

fastlane/Constants/Constant.swift
fastlane/Constants/Secret.swift
fastlane/Fastfile.swift
fastlane/Helpers/Build.swift
fastlane/Helpers/EnvironmentParser.swift
fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj/project.pbxproj

#382 
Support uploading build and dSYM files to build artifacts of CI/CD platforms.
- Create `EnvironmentParser` to read any environment variable by key; it supports getting `bool` and `string`.
- In ruby, we use `ENV["KEY_NAME"]`.
- In Swift, it becomes `environmentVariable(get: "KEY_NAME")`.
- Create a `platform` in `Constant` to determine which platform is running on.
- Also update Secret's variables by retrieve from `EnvironmentParser` based on the key:
- `KEYCHAIN_PASSWORD`
- `FIREBASE_CLI_TOKEN`
- `APPSTORE_CONNECT_API_KEY`

[#382] [Fastlane Swift] Support uploading build and dSYM files to build artifacts of CI/CD platforms

---

fastlane/swift/DeliverfileProtocol.swift
fastlane/swift/Fastlane.swift
fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj/project.pbxproj
fastlane/swift/GymfileProtocol.swift
fastlane/swift/MatchfileProtocol.swift
fastlane/swift/PrecheckfileProtocol.swift
fastlane/swift/ScanfileProtocol.swift
fastlane/swift/ScreengrabfileProtocol.swift
fastlane/swift/SnapshotfileProtocol.swift

- #388 
The template currently has a Build Phase called CopyFiles which does the same thing as FastlaneRunnerCopySigned. When both of the build phases exist at the same time, fastlane swift will fail with error:
```
❌  error: Unexpected duplicate tasks
❌  error: Unexpected duplicate tasks
** BUILD FAILED **
[10:46:28]: Exit status: 65
+-----------+-----------------------------+
|              Lane Context               |
+-----------+-----------------------------+
| LANE_NAME | syncAppStoreCodeSigningLane |
+-----------+-----------------------------+
[10:46:28]: Exit status: 65
[10:46:28]: fastlane finished with errors
```
When a user run `fastlane swift` locally without the build phase `FastlaneRunnerCopySigned`, a prompt will ask if they want to create the `FastlaneRunnerCopySigned` …

[#388] [Fastlane Swift] Rename FastlaneRunner Build Phase to mitigate risk of failing 

---

.github/workflows/deploy_production_firebase.yml
.github/workflows/deploy_staging_firebase.yml

https://github.com/nimblehq/ios-templates/issues/423
- Updated name from `deploy_Release_Firebase` to `deploy_production_firebase` for deploying production build to firebase workflow.
- Updated name from `deploy_Firbase` to `deploy_staging_firebase` for deploying staging build to firebase workflow.
- Updated their descriptions too.
N/A

[#423] Update a specific name for deploying staging build to firebase workflow

---

deliverable_setup.sh

- #432 
- Because the iOS template uses Fastlane Swift, the DeliverableConstants.rb was replaced with Constant.swift. We need to update deliverable_setup.sh to open Constants.swift instead of DeliverableConstants.rb
- Update deliverable_setup.sh files: Change from opening DeliverableConstants.rb file to Constant.swift file
https://user-images.githubusercontent.com/24598204/217412798-c5cec2f3-caa7-4844-b10f-dd9de5f79511.mov

[#432] [Bug] Fix: DeliverableConstants.rb does not exist

---

make.sh

- #438 
- After make.sh runs successfully, we should remove Workspace.swift as well as Project.swift, which Tuist does not reuse.
- Update make.sh: add command to remove Workspace.swift
https://user-images.githubusercontent.com/24598204/217414341-3adff36d-4ad2-48d3-8f24-9f4e8e21136c.mov

[#438] [Bug] Fix: Remove Workspace.swift when make.sh success

---

Podfile

In Podfile:
- Removed the fixed version of [Sourcery](https://github.com/krzysztofzablocki/Sourcery) (1.8.0)
- Replaced [Resolver](https://github.com/hmlongco/Resolver) by [Factory](https://github.com/hmlongco/Factory)
- For Sourcery, we had an issue with version `1.8.1`. Now the latest version is `2.0.1`, it added more features and also improved the performance (20%). So it's better to use the latest version.
- For the replacement of Resolver, this is the note from the author of Resolver:
> Note: Later in 2022 Resolver will be deprecated and replaced by my new dependency injection system, [Factory](https://github.com/hmlongco/Factory). Factory is compile-time safe and is smaller, lighter, and faster than Resolver. As good as Resolver is, Factory is better.
So it's time to use Factory. …

[Chore] Update Pods dependencies

---

.github/workflows/automatic_pull_request_review.yml
.github/workflows/deploy_app_store.yml
.github/workflows/deploy_production_firebase.yml
.github/workflows/deploy_staging_firebase.yml
.github/workflows/test_install_script.yml
.github/workflows/test_upload_build_to_test_flight.yml

- Close #460 
- Remove [Cancel Previous Runs Github Action ](https://github.com/styfle/cancel-workflow-action) in GitHub Workflows.
- Add Concurrency command to cancel previous Github Action run.
- We group the jobs by workflow name and pull request number or commit (branch pushed) to avoid canceling in-progress jobs from other workflows.

[#460] [Chore] Replace cancel-workflow-action to Github Action's concurrency

---

.github/workflows/automatic_pull_request_review.yml
.github/workflows/deploy_app_store.yml
.github/workflows/deploy_production_firebase.yml
.github/workflows/deploy_staging_firebase.yml
.github/workflows/test_install_script.yml
.github/workflows/test_upload_build_to_test_flight.yml

- Close #463
Updating the following actions:
- `actions/checkout@v2` -> `actions/checkout@v3`
- `webfactory/ssh-agent@v0.5.4` -> `webfactory/ssh-agent@v0.7.0`
- `actions/cache@v2` -> `actions/cache@v3`
- N/a
No more warning:

[#463] Update actions version

---

.github/workflows/test_upload_build_to_test_flight.yml
fastlane/Constants/Constant.swift
fastlane/Fastfile.swift
fastlane/Helpers/Build.swift
fastlane/Helpers/Match.swift
set_up_test_testflight.sh

- Close #https://github.com/nimblehq/ios-templates/issues/330
When generating a new project from make.sh, the Signing is automatic signing. This does not change when running fastlane match.
This causes issues:
CICD fail if the user did not modify Signing manually.
CICD fail if the user modify Signing manually but push incorrect settings.
Local build fail the user did not modify Signing manually.
Added `updateCodeSigningSettings` to update the xcode project with synced match provisioning profiles after each match sync
Added syncDevelopmentProductionCodeSigningLane since there was no lane to generate a provisioning profile for Debug Production configuration.

[#330] Modify signing automatically when generating a project

---

fastlane/Constants/Constant.swift
fastlane/Fastfile.swift
fastlane/Helpers/AppStoreAuthentication.swift
fastlane/Helpers/Match.swift

- Close #https://github.com/nimblehq/ios-templates/issues/310
Added separate username and team ids for staging and production
Didnt change appStoreConnectApiKey since it is very unlikely we need to upload both staging and production to appstore if they are using different apple accounts. 
Removed duplicated Environment enum from Match.swift

[#310] Support multiple apple portal accounts

---

Tuist/Interfaces/SwiftUI/Project/Podfile

- Close #505
Update the profile of SwiftUI project by adding a new library or removing redundant 3rd-parties. For instance, we will add FlowStacks library, which handles the navigation flow in a SwiftUI application.
Added the following libs:
- FlowStacks
- Moya/Combine
- JSONAPIMapper'
This PR must pass the CI

[#505] Set up necessary library for a SwiftUI project

---

Dangerfile
Scripts/Swift/Extensions/FileManager+Utils.swift
Scripts/Swift/Extensions/String+Utils.swift
Scripts/Swift/SetUpCICDService.swift
Scripts/Swift/SetUpDeliveryConstants.swift
Scripts/Swift/SetUpInterface.swift
Scripts/Swift/SetUpiOSProject.swift
make.sh

- Close #494
Migrate make.sh to Swift Command Line
- Keep `make.sh` for running the project with minimal change to command. Will be removed in #495 
- Add `copy` and `createDirectory` in `FileManager`.
- Add regex `~=` matcher to `String`.
- Move `SetUpCICDService` to struct to be called by `SetUpIOSProject`.
- Move `SetUpDeliveryConstants` to struct to be called by `SetUpIOSProject`.
- Move `SetUpInterface` to struct to be called by `SetUpIOSProject`.
- Create `SetUpIOSProject.swift` which will replace `make.sh`
Projects build successfully and CICD test works.

[#494] Migrate make.sh to Swift command

---

Tuist/Interfaces/UIKit/Sources/Presentation/Modules/HomeViewController.swift
{PROJECT_NAME}KIFUITests/Sources/Specs/Application/ApplicationSpec.swift

- Close #517 
- Update UI test's searching label's text
- Previously UI test waited for wrong text to appear in screen, now the texts are matched and the error is gone
- Test done on main branch as develop branch got hanged while installing dependencies

[#517] Fix: UI test crashed in initial run for SwiftUI project

---

Tuist/Interfaces/SwiftUI/Project/Podfile
Tuist/Interfaces/UIKit/Project/Podfile
{PROJECT_NAME}KIFUITests/Sources/Specs/Application/ApplicationSpec.swift
{PROJECT_NAME}KIFUITests/Sources/Utilities/KIF+Swift.swift
{PROJECT_NAME}KIFUITests/Sources/Utilities/KIFSpec.swift
{PROJECT_NAME}Tests/Sources/Specs/Data/NetworkAPI/NetworkAPISpec.swift
{PROJECT_NAME}Tests/Sources/Specs/Supports/Extensions/Foundation/OptionalUnwrapSpec.swift

- Close #482 
Update Quick and Nimble to Quick 7 and Nimble 12.
- [Quick 7](https://github.com/Quick/Quick/releases/tag/v7.0.0) supports async and non-async explicitly.
- Make default spec same as Quick 5 which we all like 😄 
- Update KIF spec to match Quick 7. 
- No more thread complain.
https://github.com/nimblehq/ios-templates/assets/6356137/2a3b794c-21f1-4258-9882-d7b0f8187acb

[#482] Migrate Quick/Nimble tests to Quick 7

---

.swiftlint.yml

- Close #478 
- Update SwiftLint implicit_return rule
- N/A

[#487] Update swiftlint implicit_return rule

---

fastlane/Helpers/Keychain.swift

- Close #528
Update timeout for keychain to no 1.2 days.
- I decided to use 1.2 days instead of no time-out because I have concern with keychains that never gets deleted could be remotely hacked.
- There will be a timer to remove keychains nightly on self-hosted.
This keychain had been unlocked for 2 hr+.

[#528] Update Default timeout for Keychain to `no time-out`

---

.github/wiki/Standard-File-Organization.md
Gemfile
Tuist/Interfaces/UIKit/Project/.sourcery.yml

- Close #530
Update Standard File Organization Wiki with SwiftUI and UIKit.
- Use same structure as Compass https://nimblehq.co/compass/development/ios/user-interface/swiftui/.
https://github.com/nimblehq/ios-templates/blob/d9d2f440aa1a8ba9462219cbd1a3a8ebe7db5526/.github/wiki/Standard-File-Organization.md

[#530] Update Standard File Organization Wiki

---

.github/project_workflows/deploy_production_firebase.yml
.github/project_workflows/deploy_staging_firebase.yml
.github/wiki/CodeMagic.md
.github/wiki/Github-Actions.md
.github/workflows/test_upload_build_to_firebase.yml
codemagic.yaml
fastlane/Constants/Secret.swift
fastlane/Helpers/Distribution.swift

- Close #522
- Replace `FIREBASE_TOKEN` from all workflows Secrets and use `FIREBASE_GOOGLE_APPLICATION_CREDENTIALS` instead.
- Update test workflow to use `FIREBASE_GOOGLE_APPLICATION_CREDENTIALS` as well.
- Not sure for `CodeMagic` and `Bitrise`
- For `CodeMagic`, I used this [document](https://docs.codemagic.io/partials/firebase-authentication-service-account/).
- For `Bitrise` it seems to be passable from the file upload section. https://devcenter.bitrise.io/en/connectivity/connecting-to-services/connecting-a-google-service-account-to-bitrise.html.  There is no `FIREBASE_TOKEN` declared in the current `Bitrise.yml` so I didn't change it.
Firebase test workflow works.

[#522] Replace Firebase Token with Google Service Account

---

.swiftformat
.swiftlint.yml
fastlane/Constants/Constant.swift
fastlane/Fastfile.swift
fastlane/Helpers/Keychain.swift
fastlane/Helpers/Match.swift
{PROJECT_NAME}KIFUITests/Sources/Utilities/KIF+Swift.swift
{PROJECT_NAME}Tests/Sources/Specs/Data/NetworkAPI/NetworkAPISpec.swift

- Close #548 
- Added ArkanaKeys in Swiftlint and swiftformat
- Removed `anyobject_protocol ` in Swiftlint
- Fixed all lints which trigger swiftlint and swiftformat on the app
- There are warnings left from Cocoapod for Sourcery, Swiftlint, and SwiftFormat. They may come from CocoaPods, there's [a thread](https://stackoverflow.com/questions/74012563/warning-build-run-script-build-phase-module-will-be-run-during-every-build-be) with solutions, but these warnings do not trigger the swiftlint and swiftformat so I think we can leave them for now
I generated a new project:

[#548] [Chore] Fix lints after generating project

---

.github/wiki/Standard-File-Organization.md

- Close #541 
- Update the file `Standard-File-Organization.md`
- Update directory tree
- Add new section `Modules` with new contents about `Data` and `Domain` modules
Update the directory structure document to reflect the new changes on #349 - Modulization `Data` and `Domain` layer.

[#541] Update the iOS template project structure to reflect the new modules 

---

.github/self_hosted_project_workflows/automatic_pull_request_review.yml
.github/self_hosted_project_workflows/deploy_app_store.yml
.github/self_hosted_project_workflows/deploy_production_firebase.yml
.github/self_hosted_project_workflows/deploy_staging_firebase.yml
.github/self_hosted_project_workflows/draft_a_new_release.yml
.github/self_hosted_project_workflows/publish_docs_to_wiki.yml
Scripts/Swift/iOSTemplateMaker/Sources/iOSTemplateMaker/SetUpCICDService.swift

- Close #498 
- Update Script: `SetUpCICDService` to ask for runner type
- We create two folders for each runner type with the same workflows but different runs-on. When the developer chooses a runner type, the chosen type will be copied to the workflow directory then remove the source folder later
- N/A

[#498] Add option: github-self-hosted while generating the project

---

PROJECT_README.md
Scripts/Swift/iOSTemplateMaker/Sources/iOSTemplateMaker/SetUpiOSProject.swift

- Close #534
- `PROJECT_README.md`
- Update `SetUpiOSProject.swift` to replace `README.md` with `PROJECT_README.md`
n/a

[#534] Add README for project setup instructions

---

.github/project_workflows/add_device_profile.yml
.github/workflows/test_swiftui_install_script.yml
Scripts/Swift/iOSTemplateMaker/Sources/iOSTemplateMaker/SetUpCICDService.swift
fastlane/Constants/Constant.swift
fastlane/Constants/Secret.swift
fastlane/Fastfile.swift
fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj/xcshareddata/xcschemes/FastlaneRunner.xcscheme

- Close #546 
- Add `add_device_profile.yml` workflow
- Add a new lane `addDevicesGenerateProfiles`
It's because we have a limitation on adding new device so I only test with a fake device information

[#546] Support adding new devices directly from Github Action

---

.github/project_workflows/configs/changelog-config.json
.github/project_workflows/create_release_pull_request.yml
.github/project_workflows/create_release_pull_request_and_bump_version.yml
Scripts/Swift/iOSTemplateMaker/Sources/iOSTemplateMaker/SetUpiOSProject.swift

- Close #557
- Add a new workflow to create a release PR
- Add a new workflow to create a bump version PR
n/a
| Bump Version | Release |
|--------|--------|
| ![CleanShot 2024-11-11 at 11 14 18](https://github.com/user-attachments/assets/0b9c4056-72f6-4f1f-8c1b-f773cb12dab0) | ![CleanShot 2024-11-11 at 10 36 40](https://github.com/user-attachments/assets/9a112829-1d4e-4ac6-8553-9025a61eb9cc) |

[#557] Automate Release Pull Request Creation Process
