__PROJECT NAME__/__PROJECT NAME__.xcodeproj/project.pbxproj

We need manual code singing for different way we build the app ( Crashlytics, DIstributions, Adhoc ... ), So I remove automatic code signing. Then setup with fastlane script. 
will close #22

Change codesiging to Manual

---

__PROJECT NAME__/__PROJECT NAME__.xcodeproj/project.pbxproj

`Fastfile` does not support `$(SRCROOT)` as Absolute Path, So I need to change this to relative path

Change Info.plist to relative path

---

__PROJECT NAME__/__PROJECT NAME__.xcodeproj/project.pbxproj

Before I was miss understood about adding app to fabric. That we're going to add only `Staging` to `Fabric` but it's not. 
We're going to add all apps bundle to `Fabric.app` but send beta for only `Staging`.

remove scheme build condition.

---

__PROJECT NAME__/Jenkinfile

- Add Jenkinsfile following work flow. 
**develop** 
**master**
**branches**
**release**
close #39

[3] Jenkins supported.

---

__PROJECT NAME__/__PROJECT NAME__.xcodeproj/project.pbxproj

- Cannot run unit test following #42 
- I set test host on unit test target.

fix unit test target host

---

Nimble Templates/App.xctemplate/Podfile
Nimble Templates/App.xctemplate/TemplateInfo.plist

https://github.com/nimbl3/ios-templates/issues/100
Add needed pods (Cocoapods) into templates:

[100] Add Podfile - Configure Bundle gems: Cocoapods

---

README.md

https://github.com/nimbl3/ios-templates/issues/138
Image paths got incorrect in README

[138] Update image paths in README

---

.sourcery.yml
.swiftlint.yml
Tuist/ProjectDescriptionHelpers/Scheme+Initializing.swift
Tuist/ProjectDescriptionHelpers/Target+Initializing.swift
Tuist/ProjectDescriptionHelpers/TargetAction+Initializing.swift
tools/sourcery/templates/AutoMockable.stencil

https://github.com/nimblehq/ios-templates/issues/173
Add run script build phase for:
- `Sourcery`
- `R.swift`
- `SwiftLint`

[173] Setup shell script Build Phase for libraries

---

.github/workflows/deploy_AppStore.yml
.github/workflows/deploy_Firebase.yml
.github/workflows/deploy_Release_Firebase.yml
.github/workflows/test.yml
Gemfile
fastlane/Constants/Constants.rb
fastlane/Fastfile
fastlane/Managers/TestManager.rb

Resolves https://github.com/nimblehq/ios-templates/issues/154
- Add `TestManager`
- Add clean up lane
- Add `Gemfile`
- Update test function to test only specific targets (tests or UI tests).
- Code signing has been implemented in #157

[154] Add Fastlane

---

Gemfile
Podfile

Resolves https://github.com/nimblehq/ios-templates/issues/155
- Setup `Podfile`
- Update `Gemfile`

[155] Add Cocoapods

---

ProjectName/Sources/Data/NetworkAPI/Core/NetworkAPIError.swift
ProjectName/Sources/Data/NetworkAPI/Core/NetworkAPIProtocol.swift
ProjectName/Sources/Data/NetworkAPI/Core/RequestConfiguration.swift
ProjectName/Sources/Data/NetworkAPI/NetworkAPI.swift
ProjectName/Sources/Domain/UseCases/UseCaseFactoryProtocol.swift
ProjectName/Sources/Presentation/Navigator/Navigator+Scene.swift
ProjectName/Sources/Presentation/Navigator/Navigator+Transition.swift
ProjectName/Sources/Presentation/Navigator/Navigator.swift
Tuist/ProjectDescriptionHelpers/Target+Initializing.swift

https://github.com/nimblehq/ios-templates/issues/166
Generating follow the structure:
```json
│       ├── Data
│       │   ├── NetworkAPI
│       │   │   ├── AuthenticatedNetworkAPI.swift
│       │   │   ├── NetworkAPI.swift
│       │   │   ├── Core
│       │   │   ├── Interceptors
│       │   │   ├── Models
│       │   │   └── RequestConfigurations
│       │   └── Repositories
│       ├── Domain
│       │   ├── Entities
│       │   ├── Interfaces
│       │   └── UseCases
│       │       ├── UseCaseProvider.swift
│       ├── Presentation
│       │   ├── Modules
│       │   ├── Navigator
│       │   │   ├── Navigator+Scene.swift
│       │   │   ├── Navigator+Transition.swift
│       │   │   └── Navigator.swift
│       │   └── Views
```
- Prepare some empty folder with `.gitkeep` inside
- …

[166] Generating: Source folder

---

.github/CODEOWNERS

Update the CODEOWNERS file in the subdirectory `.github` to support adding all reviewers from the iOS chapter.
- Add @suho to the list. This will ensure that all concerned developers (including Team Lead) are notified when new pull requests are created ✌️

Update the project's maintainers info

---

.github/CODEOWNERS

Add new iOS members to the code owners list.
- Add:
- David: @ducbm051291 
- Taher: @Shayokh144

[Chore] Add David and Taher into the Codeowners list

---

.swiftformat

https://github.com/nimblehq/ios-templates/issues/277
Update .swiftformat with --extensionacl on-declarations
n/a

[#277] Update .swiftformat with --extensionacl on-declarations

---

.github/CODEOWNERS

- Add new members @Thieurom and @nkhanh44 into CODEOWNERS
N/A

Update CODEOWNERS with new members: @Thieurom @nkhanh44

---

.github/CODEOWNERS

Update CODEOWNERS with a new Team Lead
Please check this [discussion](https://nimble-co.slack.com/archives/C418DBL2W/p1658379650460599) for the reason of this update
n/a

[Chore] Update CODEOWNERS with a new Team Lead

---

make.sh

#270 
- When run install script of ios-template, these errors occured:
- Error in Sourcetree: "fatal: Unknown index entry format 61740000" in Sourcetree
- Error in Xcode: "invalid data in index - invalid entry (-1)"
- Fixed by adding `git reset` command after `rm -f .git/index`

[#270] [Bug] Fix: Errors occurred in Xcode and Sourcetree when run install script of ios-template 

---

fastlane/Constants/Constant.swift
fastlane/Fastfile.swift
fastlane/Helpers/Build.swift
fastlane/Helpers/Distribution.swift

#333
We need all build files, ipa, and dSYM into only one folder. It will help us easier to clean up later.
- Create output path at `Constant`
- Make `Build` and `DerivedData` into `Output`
- Set `outputDirectory` when building
- Add `Lane` suffix for build and upload to firebase lanes.

[#333] As a developer, I can build the project with the adhoc and appstore methods with Fastlane Swift

---

fastlane/Constants/Constant.swift
fastlane/Constants/Secret.swift
fastlane/Fastfile.swift
fastlane/Helpers/AppStoreAuthentication.swift
fastlane/Helpers/Distribution.swift
fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj/project.pbxproj

#336
- Create `uploadToAppStore` function at `Distribution`
- Support making App Store API Key:
- Add `appstoreConnectAPIKey` in `Secret`
- Add `appStoreKeyId` and `appStoreKeyId` to `Constant`
- Rearrange `Constant` `MARK` by alphabet order
- Create lane `buildAndUploadToAppStoreLane`

[#336] As a developer, I can upload the build to App Store Connect with Fastlane Swift

---

.swiftlint.yml
README.md

https://github.com/nimblehq/ios-templates/milestone/16?closed=1
N/A
- #348 
N/A

Release - 3.11.0

---

Dangerfile

https://github.com/nimblehq/ios-templates/issues/
Describe the big picture of your changes here to communicate to the team why we should accept this pull request. 
Describe in details how to test the changes; referenced documentation is welcome as well.
Show us the implementation: screenshots, gif, etc.

[#399] Correct Constant file path

---

.github/workflows/deploy_production_firebase.yml
.github/workflows/deploy_staging_firebase.yml

https://github.com/nimblehq/ios-templates/issues/423
- Updated name from `deploy_Release_Firebase` to `deploy_production_firebase` for deploying production build to firebase workflow.
- Updated name from `deploy_Firbase` to `deploy_staging_firebase` for deploying staging build to firebase workflow.
- Updated their descriptions too.
N/A

[Chore] [#423] Update a specific name for deploying staging build to firebase workflow

---

.github/workflows/deploy_Firebase.yml
.github/workflows/deploy_Release_Firebase.yml

Revert "[Chore] [#423] Update a specific name for deploying staging build to firebase workflow"

---

.github/wiki/CodeMagic.md
.github/wiki/_Sidebar.md
Dangerfile
codemagic.yaml
deliverable_setup.sh
fastlane/Constants/Constant.swift
fastlane/Helpers/Build.swift

- #315 
- Support the Codemagic CI/CD service by adding `codemagic.yaml` in the root folder
- Create `codemagic.yaml` to store CodeMagic CI/CD workflows and configuration
- Update `deliverable_setup.sh` with CodeMagic
- Update PlatformType in Fastlane Constant with CodeMagic 
- Create a CodeMagic Wiki page and update the CodeMagic reference on the SideBar page
** There's an issue with Fastlane now; when the CodeMagic CI/CD runs the Fastlane match, this error will occur, but the Workflow deploys the application to Firebase Staging, and Production is still ok. Except for the workflow deploying the application to the app store will be stuck at building and uploading the application to the app store.
** Temporary solution is to add another Fastlane match adHoc before the match appstore.

[#315] CI/CD - Add support for Codemagic CI/CD service

---

.github/PULL_REQUEST_TEMPLATE.md

- Close #446 
- Update PULL_REQUEST_TEMPLATE.md with [latest version](https://github.com/nimblehq/git-template/blob/main/.github/PULL_REQUEST_TEMPLATE.md) from Nimble Git Template
- N/A

[#446] [Chore] Update the Pull Request Template to the latest version

---

.arkana.yml
.github/workflows/automatic_pull_request_review.yml
.github/workflows/deploy_app_store.yml
.github/workflows/deploy_production_firebase.yml
.github/workflows/deploy_staging_firebase.yml
.github/workflows/test_install_script.yml
.gitignore
Gemfile
Podfile
make.sh
{PROJECT_NAME}/Sources/Constants/Constants+API.swift

- Close #465 
Integrate Arkana to the ios template with the followings:
- Add `.arkana.yml` (Arkana Configuration file)
- Add `.env.example` (Example of .env file for Arakana)
- Add Arkana to `Gemfile` for installing bundles
- Update `make.sh` to run Arkana after installing bundles
- Update Podfile with 2 Generated Pods by Arkana
- Add sample usage in Constant+API.swift how to use Arkana
- Update workflows to run arkana
How to test: 
1. Create a `.env` file from the `.env.example` file
2. Run `make.sh`
**Run make.sh successfully with Arkana**
**Build project successfully with Arkana**

[#465] Add Arkana to store keys and secrets away from source code

---

.github/workflows/test_swiftui_install_script.yml
.github/workflows/test_uikit_install_script.yml

- Close #484 
Add installation test for SwiftUI variant of the project.
- Rename original build test Actions to UIKit test.
- Add installation script for SwiftUI.

[#484] Add Build Test for SwiftUI Project

---

Tuist/Interfaces/SwiftUI/Project/Podfile
Tuist/Interfaces/UIKit/Project/Podfile

- Close #509 
Repace Podfile hard-code version with {TARGET_VERSION}
- N/A

[#509] Minimum ios version does not match the set version when create project with template

---

.github/project_workflows/deploy_app_store.yml
.github/project_workflows/deploy_production_firebase.yml
.github/project_workflows/deploy_staging_firebase.yml

- Close #521 
Update norio-nomura/action-swiftlint to latest version 3.2.1
- N/A

[#521] [Chore]  Update SwiftLint in GitHub Workflows to the newest version

---

.github/workflows/cleanup_cache.yml
.github/workflows/test_swiftui_install_script.yml
fastlane/Constants/Constant.swift

- Close #524
- Added workflow to clear GitHub action cache
- n/a
job done at:
https://github.com/nimblehq/ios-templates/actions/runs/7540455882

[#524] Add workflow to clear GitHub action cache

---

.github/CODEOWNERS

- Close #
- Add `@dquangit @roman-nimble`
- Remove `@edgarss`
n/a
n/a

[#555] Update CODEOWNERS with new members

---

.github/CODEOWNERS

Add new members

---

.github/project_workflows/deploy_production_firebase.yml
.github/project_workflows/deploy_staging_firebase.yml
.github/workflows/test_upload_build_to_firebase.yml
fastlane/Constants/Constant.swift
fastlane/Fastfile.swift

- Close #493 
- Update workflows to add release notes when deploying to Firebase
n/a

[#493] Generate release notes when uploading builds to Firebase/TestFlight
